### ISSUE TITLE
Action documentation in README.md

### ISSUE THREAD

**Issue by materpillar** [materpillar/Capella-HTML-exporter#6]
The part https://github.com/materpillar/Capella-HTML-exporter/blob/bbee4e0a8d1acb76135c6b135dcd255c35e08b3f/README.md?plain=1#L38-L47 
should be: 

```
jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Test building HTML of IFE model
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Export and validate model
      uses: materpillar/capella-html-exporter@v6
      with:
        entrypoint: ./entrypoint.sh
        model-name: capella-automations
        path-model-folder: capella-automations
```

See example repository: https://github.com/materpillar/Capella-Automations-Model/blob/main/.github/workflows/export-validate-model.yml
